version: '2'

services:
  mysql:
    image: "mysql:8.0"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./tmp/mysql:/var/lib/mysql
  pwp:
    build: .
    image: "surma/progressivewordpress"
    environment:
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    links:
      - mysql
    volumes:
      - ./dist/theme:/var/www/html/wp-content/themes/surmblog
      - ./dist/pwp-lazy-image-plugin:/var/www/html/wp-content/plugins/pwp-lazy-image-plugin
      - ./tmp/uploads:/var/www/html/wp-content/uploads
  caddy:
    build: ./caddy
    volumes:
      - ./caddy/Caddyfile:/etc/Caddyfile
      - ./tmp/caddy:/root/.caddy
    ports:
      - localhost:8080:8080
      #- 80:80
      #- 443:443
    links:
      - pwp
