version: '2'

services:
  mysql:
    image: "mysql:8.0"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  pwp:
    build: .
    image: "surma/progressivewordpress"
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    links:
      - mysql
    volumes:
      - ./dist/theme:/var/www/html/wp-content/themes/surmblog
      - ./dist/pwp-lazy-image-plugin:/var/www/html/wp-content/plugins/pwp-lazy-image-plugin
      - ./uploads:/var/www/html/wp-content/uploadse
